### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [HiddenWoodpecker/pzrl2lab#1]
Не очень хорошо мешать .c и .o при сборке. Да и принцип инкрементной сборки нарушается, так как файл main.c компилируется всегда, вне зависимости от того, изменялся ли он. Добавьте отсутствующую цель.

**Comment by HiddenWoodpecker** [comment]
> Не очень хорошо мешать .c и .o при сборке. Да и принцип инкрементной сборки нарушается, так как файл main.c компилируется всегда, вне зависимости от того, изменялся ли он. Добавьте отсутствующую цель.

Добавил

**Comment by rredbird66** [comment]
lab2 в .gitignore нет
![изображение](https://github.com/HiddenWoodpecker/pzrl2lab/assets/36138085/1bfe1c9f-f0ed-4916-94d5-6465457d4aef)

**Comment by HiddenWoodpecker** [comment]
у меня nothing to commit, но изменил gitignore

**Comment by HiddenWoodpecker** [comment]
![image](https://github.com/HiddenWoodpecker/pzrl2lab/assets/63347713/6c8b7ad8-82b0-4b16-be7f-439611b6de66)

**Comment by rredbird66** [comment]
Теперь хорошо.
![изображение](https://github.com/HiddenWoodpecker/pzrl2lab/assets/36138085/1cff30cf-cdcf-4f8b-a30e-2ac3220e49ca)

Лабораторная 2 зачтена.
